#pragma once
//タイル画像のタイプ
enum TILE_IMAGE_TYPE
{
	TILE_IMAGE_TYPE_NONE,
	TILE_IMAGE_TYPE_UP,			//上
	TILE_IMAGE_TYPE_DOWN,		//下
	TILE_IMAGE_TYPE_RIGHT,		//右
	TILE_IMAGE_TYPE_LEFT,		//左
	TILE_IMAGE_TYPE_CENTER,		//中心
	TILE_IMAGE_TYPE_UPRIGHT,	//右上
	TILE_IMAGE_TYPE_UPLEFT,		//左上
	TILE_IMAGE_TYPE_DOWNRIGHT,	//右下
	TILE_IMAGE_TYPE_DOWNLEFT,	//左下
	TILE_IMAGE_TYPE_INVCORNER	//端(逆),
};